// Mock data for dashboard UI development (replace with DB queries later)

export const mockUser = {
  id: 'user_1',
  name: 'Alex Rivera',
  email: 'alex@example.com',
  image: null,
  isPro: false,
};

export const mockItemTypes = [
  { id: 'type_snippet', name: 'snippet', icon: 'Code', color: '#3b82f6', isSystem: true },
  { id: 'type_prompt', name: 'prompt', icon: 'Sparkles', color: '#8b5cf6', isSystem: true },
  { id: 'type_command', name: 'command', icon: 'Terminal', color: '#f97316', isSystem: true },
  { id: 'type_note', name: 'note', icon: 'StickyNote', color: '#fde047', isSystem: true },
  { id: 'type_file', name: 'file', icon: 'File', color: '#6b7280', isSystem: true },
  { id: 'type_image', name: 'image', icon: 'Image', color: '#ec4899', isSystem: true },
  { id: 'type_link', name: 'link', icon: 'Link', color: '#10b981', isSystem: true },
];

export const mockCollections = [
  {
    id: 'col_1',
    name: 'React Patterns',
    description: 'Reusable React hooks and component patterns',
    isFavorite: true,
    defaultTypeId: 'type_snippet',
    itemCount: 12,
  },
  {
    id: 'col_2',
    name: 'Python Snippets',
    description: 'Useful Python utilities and scripts',
    isFavorite: false,
    defaultTypeId: 'type_snippet',
    itemCount: 8,
  },
  {
    id: 'col_3',
    name: 'Context Files',
    description: 'AI context and system prompt files',
    isFavorite: false,
    defaultTypeId: 'type_file',
    itemCount: 5,
  },
  {
    id: 'col_4',
    name: 'Interview Prep',
    description: 'Questions, answers, and code examples',
    isFavorite: false,
    defaultTypeId: null,
    itemCount: 20,
  },
];

export const mockItems = [
  {
    id: 'item_1',
    title: 'useAuth hook',
    contentType: 'TEXT',
    content: 'export function useAuth() {\n  const session = useSession();\n  return session;\n}',
    description: 'Custom auth hook wrapping NextAuth useSession',
    isFavorite: true,
    isPinned: true,
    language: 'typescript',
    itemTypeId: 'type_snippet',
    tags: ['react', 'auth', 'hooks'],
    collectionIds: ['col_1'],
    createdAt: new Date('2025-03-10'),
    updatedAt: new Date('2025-03-10'),
  },
  {
    id: 'item_2',
    title: 'Code review prompt',
    contentType: 'TEXT',
    content: 'Review this code for bugs, performance issues, and security vulnerabilities. Be concise and actionable.',
    description: 'General purpose code review system prompt',
    isFavorite: true,
    isPinned: false,
    language: null,
    itemTypeId: 'type_prompt',
    tags: ['ai', 'code-review'],
    collectionIds: [],
    createdAt: new Date('2025-03-08'),
    updatedAt: new Date('2025-03-08'),
  },
  {
    id: 'item_3',
    title: 'git reset --hard HEAD~1',
    contentType: 'TEXT',
    content: 'git reset --hard HEAD~1',
    description: 'Undo last commit and discard changes',
    isFavorite: false,
    isPinned: false,
    language: 'bash',
    itemTypeId: 'type_command',
    tags: ['git'],
    collectionIds: [],
    createdAt: new Date('2025-03-07'),
    updatedAt: new Date('2025-03-07'),
  },
  {
    id: 'item_4',
    title: 'Postgres connection string format',
    contentType: 'TEXT',
    content: 'postgresql://USER:PASSWORD@HOST:PORT/DATABASE?schema=public',
    description: 'Standard Postgres connection string format',
    isFavorite: false,
    isPinned: false,
    language: null,
    itemTypeId: 'type_note',
    tags: ['postgres', 'database'],
    collectionIds: ['col_2'],
    createdAt: new Date('2025-03-05'),
    updatedAt: new Date('2025-03-05'),
  },
  {
    id: 'item_5',
    title: 'useFetch custom hook',
    contentType: 'TEXT',
    content: 'export function useFetch<T>(url: string) {\n  const [data, setData] = useState<T | null>(null);\n  // ...\n}',
    description: 'Generic data fetching hook with loading and error states',
    isFavorite: false,
    isPinned: false,
    language: 'typescript',
    itemTypeId: 'type_snippet',
    tags: ['react', 'hooks', 'fetch'],
    collectionIds: ['col_1'],
    createdAt: new Date('2025-03-03'),
    updatedAt: new Date('2025-03-03'),
  },
  {
    id: 'item_6',
    title: 'Tailwind CSS docs',
    contentType: 'URL',
    url: 'https://tailwindcss.com/docs',
    description: 'Official Tailwind CSS v4 documentation',
    isFavorite: true,
    isPinned: false,
    language: null,
    itemTypeId: 'type_link',
    tags: ['tailwind', 'css', 'docs'],
    collectionIds: [],
    createdAt: new Date('2025-03-01'),
    updatedAt: new Date('2025-03-01'),
  },
  {
    id: 'item_7',
    title: 'Docker compose up detached',
    contentType: 'TEXT',
    content: 'docker compose up -d',
    description: 'Start all containers in detached mode',
    isFavorite: false,
    isPinned: false,
    language: 'bash',
    itemTypeId: 'type_command',
    tags: ['docker'],
    collectionIds: [],
    createdAt: new Date('2025-02-28'),
    updatedAt: new Date('2025-02-28'),
  },
  {
    id: 'item_8',
    title: 'Python list comprehension',
    contentType: 'TEXT',
    content: 'squares = [x**2 for x in range(10) if x % 2 == 0]',
    description: 'List comprehension with conditional filter',
    isFavorite: false,
    isPinned: false,
    language: 'python',
    itemTypeId: 'type_snippet',
    tags: ['python'],
    collectionIds: ['col_2'],
    createdAt: new Date('2025-02-25'),
    updatedAt: new Date('2025-02-25'),
  },
];
