// Mock data for dashboard UI development (replace with DB queries later)

export const mockUser = {
  id: 'user_1',
  name: 'John Doe',
  email: 'john@example.com',
  image: null,
  isPro: false,
};

export const mockItemTypes = [
  { id: 'type_snippet', name: 'snippet', icon: 'Code', isSystem: true, count: 24, textClass: 'text-blue-500', bgClass: 'bg-blue-500/10', dotClass: 'bg-blue-500' },
  { id: 'type_prompt', name: 'prompt', icon: 'Sparkles', isSystem: true, count: 18, textClass: 'text-violet-500', bgClass: 'bg-violet-500/10', dotClass: 'bg-violet-500' },
  { id: 'type_command', name: 'command', icon: 'Terminal', isSystem: true, count: 15, textClass: 'text-orange-500', bgClass: 'bg-orange-500/10', dotClass: 'bg-orange-500' },
  { id: 'type_note', name: 'note', icon: 'StickyNote', isSystem: true, count: 12, textClass: 'text-yellow-300', bgClass: 'bg-yellow-300/10', dotClass: 'bg-yellow-300' },
  { id: 'type_file', name: 'file', icon: 'File', isSystem: true, count: 5, textClass: 'text-gray-400', bgClass: 'bg-gray-400/10', dotClass: 'bg-gray-400' },
  { id: 'type_image', name: 'image', icon: 'Image', isSystem: true, count: 3, textClass: 'text-pink-500', bgClass: 'bg-pink-500/10', dotClass: 'bg-pink-500' },
  { id: 'type_link', name: 'link', icon: 'Link', isSystem: true, count: 8, textClass: 'text-emerald-500', bgClass: 'bg-emerald-500/10', dotClass: 'bg-emerald-500' },
];

export const mockCollections = [
  {
    id: 'col_1',
    name: 'React Patterns',
    description: 'Common React patterns and hooks',
    isFavorite: true,
    defaultTypeId: 'type_snippet',
    itemCount: 12,
    borderClass: 'bg-blue-500',
    typeIds: ['type_snippet', 'type_note', 'type_link'],
  },
  {
    id: 'col_2',
    name: 'Python Snippets',
    description: 'Useful Python code snippets',
    isFavorite: false,
    defaultTypeId: 'type_snippet',
    itemCount: 5,
    borderClass: 'bg-blue-500',
    typeIds: ['type_snippet', 'type_note'],
  },
  {
    id: 'col_3',
    name: 'Context Files',
    description: 'AI context files for projects',
    isFavorite: true,
    defaultTypeId: 'type_file',
    itemCount: 5,
    borderClass: 'bg-orange-500',
    typeIds: ['type_file', 'type_note'],
  },
  {
    id: 'col_4',
    name: 'Interview Prep',
    description: 'Technical interview preparation',
    isFavorite: false,
    defaultTypeId: null,
    itemCount: 24,
    borderClass: 'bg-violet-500',
    typeIds: ['type_snippet', 'type_note', 'type_prompt'],
  },
  {
    id: 'col_5',
    name: 'Git Commands',
    description: 'Frequently used git commands',
    isFavorite: true,
    defaultTypeId: 'type_command',
    itemCount: 15,
    borderClass: 'bg-red-500',
    typeIds: ['type_command', 'type_note'],
  },
  {
    id: 'col_6',
    name: 'AI Prompts',
    description: 'Curated AI prompts for coding',
    isFavorite: false,
    defaultTypeId: 'type_prompt',
    itemCount: 18,
    borderClass: 'bg-violet-500',
    typeIds: ['type_prompt', 'type_note', 'type_snippet'],
  },
];

export const mockItems = [
  {
    id: 'item_1',
    title: 'useAuth Hook',
    contentType: 'TEXT',
    content: 'export function useAuth() {\n  const session = useSession();\n  return session;\n}',
    description: 'Custom authentication hook for React applications',
    isFavorite: true,
    isPinned: true,
    language: 'typescript',
    itemTypeId: 'type_snippet',
    tags: ['react', 'auth', 'hooks'],
    collectionIds: ['col_1'],
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'item_2',
    title: 'API Error Handling Pattern',
    contentType: 'TEXT',
    content: 'export async function fetchWithRetry(url: string, retries = 3) {\n  // ...\n}',
    description: 'Fetch wrapper with exponential backoff retry logic',
    isFavorite: true,
    isPinned: true,
    language: 'typescript',
    itemTypeId: 'type_snippet',
    tags: ['api', 'error', 'fetch'],
    collectionIds: ['col_1'],
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'item_3',
    title: 'Code review prompt',
    contentType: 'TEXT',
    content: 'Review this code for bugs, performance issues, and security vulnerabilities. Be concise and actionable.',
    description: 'General purpose code review system prompt',
    isFavorite: true,
    isPinned: false,
    language: null,
    itemTypeId: 'type_prompt',
    tags: ['ai', 'code-review'],
    collectionIds: ['col_6'],
    createdAt: new Date('2024-01-12'),
    updatedAt: new Date('2024-01-12'),
  },
  {
    id: 'item_4',
    title: 'git reset --hard HEAD~1',
    contentType: 'TEXT',
    content: 'git reset --hard HEAD~1',
    description: 'Undo last commit and discard changes',
    isFavorite: false,
    isPinned: false,
    language: 'bash',
    itemTypeId: 'type_command',
    tags: ['git'],
    collectionIds: ['col_5'],
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-10'),
  },
  {
    id: 'item_5',
    title: 'Postgres connection string format',
    contentType: 'TEXT',
    content: 'postgresql://USER:PASSWORD@HOST:PORT/DATABASE?schema=public',
    description: 'Standard Postgres connection string format',
    isFavorite: false,
    isPinned: false,
    language: null,
    itemTypeId: 'type_note',
    tags: ['postgres', 'database'],
    collectionIds: ['col_4'],
    createdAt: new Date('2024-01-08'),
    updatedAt: new Date('2024-01-08'),
  },
  {
    id: 'item_6',
    title: 'useFetch custom hook',
    contentType: 'TEXT',
    content: 'export function useFetch<T>(url: string) {\n  const [data, setData] = useState<T | null>(null);\n  // ...\n}',
    description: 'Generic data fetching hook with loading and error states',
    isFavorite: false,
    isPinned: false,
    language: 'typescript',
    itemTypeId: 'type_snippet',
    tags: ['react', 'hooks', 'fetch'],
    collectionIds: ['col_1'],
    createdAt: new Date('2024-01-06'),
    updatedAt: new Date('2024-01-06'),
  },
  {
    id: 'item_7',
    title: 'Tailwind CSS docs',
    contentType: 'URL',
    url: 'https://tailwindcss.com/docs',
    description: 'Official Tailwind CSS v4 documentation',
    isFavorite: true,
    isPinned: false,
    language: null,
    itemTypeId: 'type_link',
    tags: ['tailwind', 'css', 'docs'],
    collectionIds: [],
    createdAt: new Date('2024-01-04'),
    updatedAt: new Date('2024-01-04'),
  },
  {
    id: 'item_8',
    title: 'Docker compose up detached',
    contentType: 'TEXT',
    content: 'docker compose up -d',
    description: 'Start all containers in detached mode',
    isFavorite: false,
    isPinned: false,
    language: 'bash',
    itemTypeId: 'type_command',
    tags: ['docker'],
    collectionIds: ['col_5'],
    createdAt: new Date('2024-01-03'),
    updatedAt: new Date('2024-01-03'),
  },
  {
    id: 'item_9',
    title: 'Python list comprehension',
    contentType: 'TEXT',
    content: 'squares = [x**2 for x in range(10) if x % 2 == 0]',
    description: 'List comprehension with conditional filter',
    isFavorite: false,
    isPinned: false,
    language: 'python',
    itemTypeId: 'type_snippet',
    tags: ['python'],
    collectionIds: ['col_2'],
    createdAt: new Date('2024-01-02'),
    updatedAt: new Date('2024-01-02'),
  },
  {
    id: 'item_10',
    title: 'React Query setup',
    contentType: 'TEXT',
    content: 'const queryClient = new QueryClient();\n// wrap app in <QueryClientProvider client={queryClient}>',
    description: 'Boilerplate for setting up React Query in a Next.js app',
    isFavorite: false,
    isPinned: false,
    language: 'typescript',
    itemTypeId: 'type_snippet',
    tags: ['react', 'query', 'nextjs'],
    collectionIds: ['col_1'],
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
];
